"""Run a fixed set of questions through the assistant and write sample_questions.md.

The README needs sample questions with real outputs, and hand-copying terminal
output invites drift between what the file claims and what the code does. This
script regenerates that file from an actual run, so the documented answers are
always answers this pipeline really produced.

    python transcript.py                       # writes sample_questions.md
    python transcript.py --backend ollama --model llama3
"""
import argparse
import time
from datetime import date

from rag.embeddings import DEFAULT_MODEL
from rag.generate import BACKENDS
from rag.pipeline import Answer, Assistant
from rag.store import DEFAULT_DIR

# Chosen to exercise different retrieval behaviours, not just to look good:
# a definition, a specific number, a comparison spanning two documents, a
# question whose wording does not match the paper's wording, and one the corpus
# genuinely cannot answer.
SHOWCASE = [
    ("Single-document definition",
     "What is multi-head attention and why is it used instead of a single attention head?"),
    ("Specific factual lookup",
     "What are the default values of beta1, beta2 and epsilon in the Adam optimizer?"),
    ("Cross-document comparison",
     "How do BERT and GPT-3 differ in the way they are pre-trained?"),
    ("Paraphrased wording",
     "Why can't you just make a plain convolutional network deeper and deeper?"),
    ("Mechanism question",
     "How does LoRA reduce the number of trainable parameters during fine-tuning?"),
    ("Definition inside one paper",
     "What is the difference between RAG-Sequence and RAG-Token?"),
    ("Out of scope (should refuse)",
     "What was Nvidia's share price last Friday?"),
]


def parse_args():
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("-k", type=int, default=5)
    parser.add_argument("--store", default=DEFAULT_DIR)
    parser.add_argument("--embed-model", default=DEFAULT_MODEL)
    parser.add_argument("--backend", default="hf", choices=sorted(BACKENDS))
    parser.add_argument("--model", default=None)
    parser.add_argument("--device", default="auto")
    parser.add_argument("--out", default="sample_questions.md")
    parser.add_argument("--retrieval-only", action="store_true",
                        help="record the retrieved passages without calling the LLM")
    return parser.parse_args()


def main():
    args = parse_args()
    assistant = Assistant(
        persist_dir=args.store, embed_model=args.embed_model, device=args.device,
        backend=args.backend, model_name=args.model,
    )
    model_label = "not run (--retrieval-only)" if args.retrieval_only else (
        args.model or BACKENDS[args.backend][1])

    lines = [
        "# Sample questions and outputs",
        "",
        f"Generated by `python transcript.py` on {date.today().isoformat()} — every answer",
        "below is verbatim output from this pipeline, not edited by hand.",
        "",
        "| | |",
        "|---|---|",
        f"| Corpus | {len(assistant.store)} chunks from {len(assistant.store.sources())} documents |",
        f"| Embedding model | `{args.embed_model}` |",
        f"| Generation model | `{model_label}` (backend `{args.backend}`) |",
        f"| Passages per question | k = {args.k} |",
        "",
        "Passages marked ✅ are the ones the model cited in its answer."
        if not args.retrieval_only else
        "Retrieval-only run: this records exactly which passages reach the prompt. "
        "Re-run without --retrieval-only to include the generated answers.",
        "",
        "---",
        "",
    ]

    for label, question in SHOWCASE:
        print(f"→ {question}")
        started = time.perf_counter()
        if args.retrieval_only:
            answer = Answer(question, "_(retrieval-only run — no answer generated)_",
                            assistant.retrieve(question, k=args.k))
        else:
            answer = assistant.answer(question, k=args.k)
        elapsed = time.perf_counter() - started
        cited = set(answer.cited())

        lines += [
            f"### {label}",
            "",
            f"**Q: {question}**",
            "",
            "> " + answer.text.replace("\n", "\n> "),
            "",
            f"<details open><summary>Retrieved passages ({elapsed:.1f}s)</summary>",
            "",
        ]
        for number, hit in enumerate(answer.hits, start=1):
            mark = " ✅" if number in cited else ""
            snippet = " ".join(hit["text"].split())[:280]
            lines += [
                f"**[{number}]** `{hit['source']}` p.{hit['page']} "
                f"— similarity {hit['score']:.3f}{mark}  ",
                f"{snippet}…",
                "",
            ]
        lines += ["</details>", "", "---", ""]

    with open(args.out, "w", encoding="utf-8") as handle:
        handle.write("\n".join(lines))
    print(f"\nWrote {args.out}")


if __name__ == "__main__":
    main()
